Merge HugeCTR Backend to Triton Inference Server repo
triton-inference-server/hugectr_backend pull request #1
Opened 2021-02-09 09:23 UTC by yingcanw

To merge hugectr_inference_backend from gitlab to hugectr_backend main branch of triton inference server repo

2021-02-10 19:04 UTC, deadeyegoodwin requested changes

2021-02-10 19:04 UTC, deadeyegoodwin commented on .gitlab-ci.yml
> +include:
Do not add gitlab file to this repo

2021-02-11 01:17 UTC, yingcanw commented on .gitlab-ci.yml
> +include:
Done

2021-02-12 17:33 UTC, deadeyegoodwin approved these changes

2021-02-16 16:13 UTC, merged